Cleanup stages/archlinux/packageinstall
- Display missing dependencies after checking all of them

- Fix syntax error: if -> fi

diff --git a/stages/archlinux/packageinstall b/stages/archlinux/packageinstall
--- a/stages/archlinux/packageinstall
+++ b/stages/archlinux/packageinstall
@@ -1,15 +1,13 @@
 #!/bin/bash
 dependencies=('virtualgl-bin' 'dkms-nvidia' 'nvidia-utils-bumblebee')
-dep_met=true
-for i in "${dependencies[@]}"
-do
-    if ! $PACMAN -Qq $i&>/dev/null; then
-        echo "Missing dependency: $i"
-        dep_met=false
+missing_dependencies=()
+for package in "${dependencies[@]}"; do
+    if ! "$PACMAN" -Qq "$package" &>/dev/null; then
+        missing_dependencies[${#missing_dependencies}]="$package"
     fi
 done
-if ! dep_met; then
-    echo "You must install dependencies manually. Those packacages are \\
-    available in the AUR: $dependencies"
+if [ ${#missing_dependencies} -gt 0 ]; then
+    echo "Missing dependencies: ${missing_dependencies[*]}"
+    echo "These packages are available from the AUR"
     exit 2
-if
+fi
