Functions "{start,stop}_x" now accepts one argument for logging destination

diff --git a/install-files/bumblebee b/install-files/bumblebee
--- a/install-files/bumblebee
+++ b/install-files/bumblebee
@@ -84,49 +84,55 @@ log_close() {
 }
 
 # Start Bumblebee's X server running on the nvidia card
+# Arguments:
+# $1 - The log destination (daemon | local) if not given, "daemon" is assumed
 # Return values:
 # 0 - X server is available
 # 1 - X server is not available
 start_x() {
+    local log='daemon'
+    if [ "$1" = 'local' ]; then
+        log='local'
+    fi
     # is a X server running?
-    log_msg "daemon" "Checking for X server availability before starting X..."
+    log_msg $log "Checking for X server availability before starting X..."
     xserver_available "$PIDFILE" "$X_DAEMON" "$X_DAEMON_ARGS" >/dev/null
     case $? in
       [05]) # already started
-        log_msg "daemon" "X server is already started"
+        log_msg $log "X server is already started"
         return 0
         ;;
       1) # not started, see below
-        log_msg "daemon" "X server is not started"
+        log_msg $log "X server is not started"
         ;;
       2) # ignore pidfile, start X
-        log_msg "daemon" "Pidfile does already exist and will be removed."
+        log_msg $log "Pidfile does already exist and will be removed."
         rm -rf "$PIDFILE"
         ;;
       3) # driver crash
-        log_msg "daemon" "Xorg was previously crashed by the nvidia driver on display $VGL_DISPLAY."
-        log_msg "daemon" "  Reboot the machine if you want to use Bumblebee"
+        log_msg $log "Xorg was previously crashed by the nvidia driver on display $VGL_DISPLAY."
+        log_msg $log "  Reboot the machine if you want to use Bumblebee"
         return 1
         ;;
       4) # another X is running
-        log_msg "daemon" "Display $VGL_DISPLAY is already in use by an other program."
-        log_msg "daemon" "  Consider changing \$VGL_DISPLAY in $BUMBLEBEE_CONFDIR/bumblebee.conf"
+        log_msg $log "Display $VGL_DISPLAY is already in use by an other program."
+        log_msg $log "  Consider changing \$VGL_DISPLAY in $BUMBLEBEE_CONFDIR/bumblebee.conf"
         return 1
         ;;
     esac
 
-    log_msg "daemon" "Enabling graphics card (loading driver)..."
-    if ! log_msg "daemon" "$(enable_graphics 2>&1)"; then
-        log_msg "daemon" "The graphics card could not be enabled, perhaps the drivers failed to load."
+    log_msg $log "Enabling graphics card (loading driver)..."
+    if ! log_msg $log "$(enable_graphics 2>&1)"; then
+        log_msg $log "The graphics card could not be enabled, perhaps the drivers failed to load."
         return 1
     fi
 
-    log_msg "daemon" "Starting X..."
+    log_msg $log "Starting X..."
 
     LD_LIBRARY_PATH="$X_LD_LIBRARY_PATH:$LD_LIBRARY_PATH" \
         "$X_DAEMON" $X_DAEMON_ARGS $VGL_DISPLAY &
 
-    log_msg "daemon" "Waiting for X server to become available..."
+    log_msg $log "Waiting for X server to become available..."
     local retries max_retry_count=$(($X_SERVER_TIMEOUT * 2))
     # wait until the PIDFILE has become available (X is started)
     for ((retries=0; retries<$max_retry_count; retries++)); do
@@ -141,39 +147,42 @@ start_x() {
     xserver_available "$PIDFILE" "$X_DAEMON" "$X_DAEMON_ARGS" >/dev/null
     case $? in
       0) # OK
-        log_msg "daemon" "X needed $retries retries to become ready"
+        log_msg $log "X needed $retries retries to become ready"
         ;;
       5)
-        log_msg "daemon" "X has not become ready after $max_retry_count retries with delays of 500ms"
-        log_msg "daemon" "This could be a bug in X, please check $X_LOGFILE"
+        log_msg $log "X has not become ready after $max_retry_count retries with delays of 500ms"
+        log_msg $log "This could be a bug in X, please check $X_LOGFILE"
         return 1
         ;;
       *)
-        log_msg "daemon" "The Bumblebee X server failed to start. Please check $X_LOGFILE"
+        log_msg $log "The Bumblebee X server failed to start. Please check $X_LOGFILE"
         return 1
         ;;
     esac
 
-    log_msg "daemon" "X has started."
+    log_msg $log "X has started."
     # Everything is OK, X has started
     return 0
 }
 
 # Stop the running X server
+# Arguments:
+# $1 - The log destination (daemon | local) if not given, "daemon" is assumed
 # Return values:
 # 0 - the X server has gone (either it wasn't started or it was stopped)
 # 1 - the X server refused to leave, perhaps a driver crash
 stop_x() {
+    local log='daemon'
     local pid
     # is a X server running?
-    log_msg "daemon" "Checking for X server availability before stopping it..."
+    log_msg $log "Checking for X server availability before stopping it..."
     pid=$(xserver_available "$PIDFILE" "$X_DAEMON" "$X_DAEMON_ARGS")
     case $? in
       0) # It's our server, should stop it
-        log_msg "daemon" "X is running, initiating shutdown..."
+        log_msg $log "X is running, initiating shutdown..."
         kill -TERM "$pid" 2>/dev/null
 
-        log_msg "daemon" "Waiting for X server to stop..."
+        log_msg $log "Waiting for X server to stop..."
         # wait for at most five seconds to death
         local retries=0
         # wait until pid is no more
@@ -184,33 +193,33 @@ stop_x() {
 
         # check if still running, if it is KILL it
         if kill -0 "$pid" 2>/dev/null; then
-            log_msg "daemon" "X did not shutdown in time, sending KILL signal"
+            log_msg $log "X did not shutdown in time, sending KILL signal"
             kill -KILL "$pid" 2>/dev/null
         fi
 
         # still running? ow, perhaps a driver crash :?
         if kill -0 "$pid" 2>/dev/null; then
-            log_msg "daemon" "X could not be killed, perhaps the driver crashed?"
+            log_msg $log "X could not be killed, perhaps the driver crashed?"
             return 1
         fi
         ;;
       1|2) # not started or invalid pidfile
-        log_msg "daemon" "The X server has not started or the pidfile is invalid."
+        log_msg $log "The X server has not started or the pidfile is invalid."
         ;;
       3) # crashed, should do a cleanup?
-        log_msg "daemon" "X could not be stopped because the driver had crashed."
+        log_msg $log "X could not be stopped because the driver had crashed."
         return 1
         ;;
       4) # Not our server, not our responsibility, don't care.
         ;;
     esac
 
-    log_msg "daemon" "X is stopped."
+    log_msg $log "X is stopped."
 
-    log_msg "daemon" "Disabling graphics card (unloading driver)..."
-    if ! log_msg "daemon" "$(disable_graphics 2>&1)"; then
-        log_msg "daemon" "The card could not be disabled or the drivers failed to unload."
-        log_msg "daemon" "Perhaps an other program is utilizing the card."
+    log_msg $log "Disabling graphics card (unloading driver)..."
+    if ! log_msg $log "$(disable_graphics 2>&1)"; then
+        log_msg $log "The card could not be disabled or the drivers failed to unload."
+        log_msg $log "Perhaps an other program is utilizing the card."
     fi
 
     # Everything OK, We are gone!
