More work on start_x
- $VGL_DISPLAY should be appended to $X_DAEMON_ARGS instead of $display

- Do not add the display number in $X_DAEMON_ARGS, but use it when
  starting X

- Properly return on start_x, document return values

- Lowered delays between checking if X has started

- Added forgotten parameters to xserver_available

diff --git a/install-files/bumblebee b/install-files/bumblebee
--- a/install-files/bumblebee
+++ b/install-files/bumblebee
@@ -29,7 +29,6 @@ X_DAEMON_ARGS="-config /etc/X11/xorg.conf.nvidia -sharevts -modulepath $X_MODULE
 display=${VGL_DISPLAY##*:}
 # Remove dot and everything after it: 1.0 -> 0
 display=${display%%.*}
-X_DAEMON_ARGS="$X_DAEMON_ARGS $display"
 PIDFILE="/tmp/.X${display}-lock"
 X_LOG="/var/log/Xorg.${display}.log"
 
@@ -63,40 +62,49 @@ log_daemon_msg() {
     echo "$1"
 }
 
+# Start Bumblebee's X server running on the nvidia card
+# Return values:
+# 0 - X server is available
+# 1 - X server is not available
 start_x() {
     # is a X server running?
     xserver_available "$PIDFILE" "$X_DAEMON" "$X_DAEMON_ARGS" >/dev/null
     case $? in
       0) # already started
+        return 0
         ;;
-      1) # not started
+      1) # not started, see below
         ;;
-      2)
+      2) # ignore pidfile, start X
         rm -rf "$PIDFILE"
         ;;
       3) # driver crash
         log_daemon_msg "Xorg was previously crashed by the nvidia driver on display $VGL_DISPLAY."
         log_daemon_msg "Reboot the machine if you want to use Bumblebee"
+        return 1
         ;;
       4) # another X is running
-        log_daemon_msg "Display $VGL_DISPLAY is already in use, consider changing \$VGL_DISPLAY in /etc/bumblebee/bumblebee.conf"
+        log_daemon_msg "Display $VGL_DISPLAY is already in use."
+        log_daemon_msg "Consider changing \$VGL_DISPLAY in $BUMBLEBEE_CONFDIR/bumblebee.conf"
+        return 1
         ;;
     esac
 
     LD_LIBRARY_PATH="$X_LD_LIBRARY_PATH" \
-        "$X_DAEMON" "$X_DAEMON_ARGS" &
+        "$X_DAEMON" "$X_DAEMON_ARGS $VGL_DISPLAY" &
 
     # wait for at most three seconds before the server has started
     local retries=0
-    while [ ! -s "$PIDFILE" -a $retries -lt 3 ]; do
-        retries=`expr $retries + 1`
-        sleep 1
+    # wait until the PIDFILE has become available (X is started)
+    while [ ! -s "$PIDFILE" -a $retries -lt 6 ]; do
+        ((retries++))
+        sleep .5
     done
 
     # fail if the X server is not running
-    if ! xserver_available; then
+    if ! xserver_available "$PIDFILE" "$X_DAEMON" "$X_DAEMON_ARGS"; then
         log_daemon_msg "The Bumblebee X Server failed to start. Please check $X_LOG"
-        return 2
+        return 1
     fi
 
     # Everything is OK, X has started
