Revert "Changed name to "load_graphcis_driver" to "sanity_check""
This reverts commit e5340dc2c5ec84aabc6e06ed8309642ce2540aa6.

This will interfere with acpi-framework

diff --git a/install-files/common-functions b/install-files/common-functions
--- a/install-files/common-functions
+++ b/install-files/common-functions
@@ -70,21 +70,16 @@ get_conflicting_drivers() {
 # In the future, {en,dis}able_graphics may handle ACPI calls. Only use
 # {,un}load_graphics_driver if the card should not be toggled
 enable_graphics() {
-    # sanity check on specified driver (only nvidia is supported right now)
-    sanity_check nvidia
+    load_graphics_driver
 }
 disable_graphics() {
-    : #unload_graphics_driver
+    unload_graphics_driver
 }
 
-# Run a sanity check on the specified driver in $1. It will try to correct if
-# the wrong driver is inserted.
-# Returns
-# 0 - sanity check passed or driver corrected succesfully
-# 1 - could not satisfy driver configuration
-sanity_check() {
+# load the driver, return 1 on failure
+load_graphics_driver() {
     local remove_driver
-    local driver="$1"
+    local driver="$(get_graphics_driver)"
     if ! lsmod | grep -q "^$driver "; then
         for remove_driver in $(get_conflicting_drivers "$driver"); do
             # unload conflicting drivers if loaded, ignore failure
@@ -92,12 +87,10 @@ sanity_check() {
                 "${MODPROBE}" -r "$remove_driver"
             fi
         done
-        "${MODPROBE}" "$driver" || return 1
+      "${MODPROBE}" "$driver" || return 1
     fi
     return 0
 }
-
-# We shouldn't remove the driver unless it is absolutely necessary!!!
 # unload the driver, return 1 on failure. If the driver was already loaded, no
 # action is performed
 unload_graphics_driver() {
