Warn about cleanup requirement in ubuntu/checkdependencies

diff --git a/stages/ubuntu/checkdependencies b/stages/ubuntu/checkdependencies
--- a/stages/ubuntu/checkdependencies
+++ b/stages/ubuntu/checkdependencies
@@ -12,6 +12,18 @@ for package in "${dependencies[@]}"; do
         missing_dependencies[${#missing_dependencies}]="$package"
     fi
 done
+
+failed=false
+# detect if cleanup is needed
+if [ -f /etc/bumblebee ]; then
+    echo "The installer detected an ancient installation of Bumblebee, possibly"
+    echo "from the PPA mj-casalogic/bumblebee or git MrMEEE/bumblebee. Since"
+    echo "that version has a lot of flaws, you will need to run the cleanup"
+    echo "script first which can be done by running:"
+    echo "    sudo ./cleanup"
+    failed=true
+fi
+
 if [ ${#missing_dependencies} -gt 0 ]; then
     # bumblebee is unlikely to be installed with missing these dependencies, so
     # we can skip checks whether we've installed the bumblebee package or not
@@ -21,11 +33,15 @@ if [ ${#missing_dependencies} -gt 0 ]; then
     echo "Update your package lists and install the dependencies by running:"
     echo "    sudo apt-get update"
     echo "    sudo apt-get install ${missing_dependencies[*]}"
-    exit 4
-elif pkg_is_installed bumblebee; then
+    failed=true
+fi
+
+if pkg_is_installed bumblebee; then
     echo "The 'bumblebee' package is already installed (from a PPA?). Before"
     echo "this version can be installed, that package must be removed. That"
     echo "can be done by running:"
     echo "    sudo apt-get remove bumblebee"
-    exit 4
+    failed=true
 fi
+
+$failed && exit 4
