Update exitcode of detecthardware, rephrase text (GH-14)

diff --git a/stages/detecthardware b/stages/detecthardware
--- a/stages/detecthardware
+++ b/stages/detecthardware
@@ -28,6 +28,6 @@ case $(wc -l <<<"$NVIDIABUSID") in
 esac
 
 if [ -z "$NVIDIABUSID" ]; then
-    echo "Aborting installation"
-    exit 1
+    echo "Installation aborted."
+    exit 8
 fi
