Changed stages/ structure to separate distros

diff --git a/stages/determinedistro b/stages/determinedistro
--- a/stages/determinedistro
+++ b/stages/determinedistro
@@ -1,40 +1,40 @@
-if [ `cat /etc/issue |grep -nir fedora |wc -l` -gt 0 ]; then
-  DISTRO=FEDORA
-elif [ `cat /etc/issue |grep -nir ubuntu |wc -l` -gt 0 ] || [ `cat /etc/issue |grep -nir "Linux Mint" |wc -l` -gt 0 ] || [ `cat /etc/issue |grep -nir "Backtrack 5" |wc -l` -gt 0 ]; then
-  DISTRO=UBUNTU
-elif [ `cat /etc/issue |grep -nir openSUSE |wc -l` -gt 0 ]; then
-  DISTRO=OPENSUSE
-elif [ `cat /etc/issue |grep -nir debian |wc -l` -gt 0 ]; then
-  DISTRO=DEBIAN
-  echo "You are running Debian Linux, please see the debumblebee project for support:"
-  echo 
-  echo "https://github.com/z0rc/debumblebee"
-  echo
-  read
-  exit 1
-elif [ `cat /etc/issue |grep -nir "Arch Linux" |wc -l` -gt 0  ]; then
-  DISTRO=ARCH
-  echo "You are running Arch Linux, please see the buildscript here for support:"
-  echo
-  echo "http://aur.archlinux.org/packages.php?ID=49469"
-  echo
-  echo "Support Here: https://github.com/Samsagax/bumblebee"
-  echo 
-  read
-  exit 1
-elif [ `cat /etc/issue |grep -nir "gentoo" |wc -l` -gt 0  ]; then
-  DISTRO=GENTOO
-  echo "You are running Gentoo Linux, please see the ebuild here for support:"
-  echo
-  echo "https://github.com/iegor/bumblebee-Gentoo-support"
-  echo
-  read
-  exit 1
+if grep -iq Fedora /etc/issue; then
+    DISTRO=fedora
+elif grep -iqE 'Ubuntu|Linux Mint|Backtrack 5' /etc/issue; then
+    DISTRO=ubuntu
+elif grep -iq OpenSUSE /etc/issue; then
+    DISTRO=opensuse
+elif grep -iq Debian /etc/issue; then
+    DISTRO=debian
+    echo "You are running Debian Linux, please see the debumblebee project for support:"
+    echo 
+    echo "https://github.com/z0rc/debumblebee"
+    echo
+    read
+    exit 1
+elif grep -iq "Arch Linux" /etc/issue; then
+    DISTRO=arch
+    echo "You are running Arch Linux, please see the buildscript here for support:"
+    echo
+    echo "http://aur.archlinux.org/packages.php?ID=49469"
+    echo
+    echo "Support Here: https://github.com/Samsagax/bumblebee"
+    echo 
+    read
+    exit 1
+elif grep -iq "Gentoo" /etc/issue; then
+    DISTRO=gentoo
+    echo "You are running Gentoo Linux, please see the ebuild here for support:"
+    echo
+    echo "https://github.com/iegor/bumblebee-Gentoo-support"
+    echo
+    read
+    exit 1
 else
- echo 
- echo "Your Distribution could not be determined or is not supported."
- echo "Please report a bug at:"
- echo
- echo "https://github.com/MrMEEE/bumblebee/issues"
- exit 1
+    echo 
+    echo "Your Distribution could not be determined or is not supported."
+    echo "Please report a bug at:"
+    echo
+    echo "https://github.com/MrMEEE/bumblebee/issues"
+    exit 1
 fi
diff --git a/stages/ubuntu/installbumblebee b/stages/ubuntu/installbumblebee
--- a/stages/ubuntu/installbumblebee
+++ b/stages/ubuntu/installbumblebee
@@ -1,22 +1,22 @@
 VERSION=`cat /etc/issue | cut -f2 -d" "`
 if [ ! -f /usr/local/bin/bumblebee-disablecard-on-powerup ]; then
- # Not installed
- cp install-files/bumblebee-disablecard-on-powerup /usr/local/bin/
- ln -s /usr/local/bin/bumblebee-disablecard-on-powerup /etc/pm/power.d/
+    # Not installed
+    cp install-files/bumblebee-disablecard-on-powerup /usr/local/bin/
+    ln -s /usr/local/bin/bumblebee-disablecard-on-powerup /etc/pm/power.d/
 else
- # Already Exists
- echo
- echo "nVidia card disable-on-powerup-script: /usr/local/bin/bumblebee-disablecard-on-powerup, already exists not overwriting"
- echo
+    # Already Exists
+    echo
+    echo "nVidia card disable-on-powerup-script: /usr/local/bin/bumblebee-disablecard-on-powerup, already exists not overwriting"
+    echo
 fi
 
 if [ -f /etc/default/bumblebee ]; then
-  # Already Exists
-  echo
-  echo "Default settings file: /etc/default/bumblebee, already exists."
-  echo "Installing new, old configuration file saved as: /etc/default/bumblebee.old."
-  echo
-  mv /etc/default/bumblebee /etc/default/bumblebee.old
+    # Already Exists
+    echo
+    echo "Default settings file: /etc/default/bumblebee, already exists."
+    echo "Installing new, old configuration file saved as: /etc/default/bumblebee.old."
+    echo
+    mv /etc/default/bumblebee /etc/default/bumblebee.old
 fi
 
 cp install-files/bumblebee.default /etc/default/bumblebee
@@ -26,21 +26,21 @@ cp install-files/documentation /usr/share/doc/bumblebee
 cp install-files/ubuntu/* /usr/share/doc/bumblebee
 
 if [ "$ARCH" = "x86_64" ]; then
- echo
- echo "64-bit system detected"
- echo
- dpkg -i install-files/VirtualGL_amd64.deb
+    echo
+    echo "64-bit system detected"
+    echo
+    dpkg -i install-files/VirtualGL_amd64.deb
 elif [ "$ARCH" = "i686" ]; then
- echo
- echo "32-bit system detected"
- echo
- dpkg -i install-files/VirtualGL_i386.deb
+    echo
+    echo "32-bit system detected"
+    echo
+    dpkg -i install-files/VirtualGL_i386.deb
 fi
 if [ $? -ne 0 ]; then
- echo
- echo "Package manager failed to install VirtualGL..."
- echo
- exit 20
+    echo
+    echo "Package manager failed to install VirtualGL..."
+    echo
+    exit 20
 fi
 cp install-files/bumblebee.script.ubuntu /etc/init.d/bumblebee
 
@@ -70,12 +70,12 @@ cp install-files/bumblebee.script.ubuntu /etc/init.d/bumblebee
 for arch in x86_64-linux-gnu i386-linux-gnu; do
 	# check if the link exist to prevent error messages
 	if update-alternatives --list ${arch}_gl_conf >/dev/null 2>&1; then
-		update-alternatives --force --set ${arch}_gl_conf /usr/lib/$arch/mesa/ld.so.conf
+	    update-alternatives --force --set ${arch}_gl_conf /usr/lib/$arch/mesa/ld.so.conf
 	fi
 done
 # versions before Oneiric without multiarch
 if update-alternatives --list gl_conf >/dev/null 2>&1; then
-	update-alternatives --force --set gl_conf /usr/lib/mesa/ld.so.conf
+    update-alternatives --force --set gl_conf /usr/lib/mesa/ld.so.conf
 fi
 # remove a legacy link which was not used anyway
 rm -rf /etc/alternatives/xorg_extra_modules-bumblebee
@@ -91,11 +91,10 @@ cp install-files/optirun.bash_completion /etc/bash_completion.d/optirun
 cp install-files/optirun.ubuntu /usr/local/bin/optirun
 
 if [ "$ARCH" = "x86_64" ]; then
- ln -s /usr/local/bin/optirun /usr/local/bin/optirun32
- ln -s /usr/local/bin/optirun /usr/local/bin/optirun64
+    ln -s /usr/local/bin/optirun /usr/local/bin/optirun32
+    ln -s /usr/local/bin/optirun /usr/local/bin/optirun64
 fi
 
 if [ "`cat /etc/modules |grep "nvidia-current" |wc -l`" -eq "0" ]; then
-  echo "nvidia-current" >> /etc/modules
+    echo "nvidia-current" >> /etc/modules
 fi
-
diff --git a/stages/ubuntu/packageinstall b/stages/ubuntu/packageinstall
--- a/stages/ubuntu/packageinstall
+++ b/stages/ubuntu/packageinstall
@@ -1,12 +1,15 @@
 VERSION=`cat /etc/issue | cut -f2 -d" "`
+
 apt-add-repository ppa:ubuntu-x-swat/x-updates
 apt-get update
 apt-get -y install nvidia-current
+
 if [ $? -ne 0 ]; then
- echo
- echo "Package manager failed to install needed packages..."
- echo
- exit 1
+    echo
+    echo "Package manager failed to install needed packages."
+    echo
+    exit 1
 fi
+
 ${MODPROBE} -r nouveau
 ${MODPROBE} nvidia-current
