Updated uninstall step from installation
Removed old things done in order to clean MrMEEE version.

diff --git a/stages/uninstall b/stages/uninstall
--- a/stages/uninstall
+++ b/stages/uninstall
@@ -3,14 +3,12 @@
 uninstall_opts=('--upgrade')
 $UNATTENDED && uninstall_opts[${#uninstall_opts[@]}]='--unattended'
 
-for uninstaller in /usr/local/bin/bumblebee-uninstall \
-    "$BINDIR/bumblebee-uninstall"; do
-    if [ -x "$uninstaller" ]; then
-        echo "Running $uninstaller..."
-        if ! "$uninstaller" "${uninstall_opts[@]}"; then
-            echo "Uninstallation failed, installation aborted."
-            exit 5
-        fi
-        break
+uninstaller="$BINDIR/bumblebee-uninstall"
+if [ -x "$uninstaller" ]; then
+    echo "Running $uninstaller..."
+    if ! "$uninstaller" "${uninstall_opts[@]}"; then
+        echo "Uninstallation failed, installation aborted."
+        exit 5
     fi
-done
+    break
+fi
