Start with new installer
- Store version in VERSION

- New installer (note: incomplete)

- One file for privilege check

- Accept command-line options (--unattended) and store variables in one file

diff --git a/stages/welcome b/stages/welcome
--- a/stages/welcome
+++ b/stages/welcome
@@ -1,20 +1,16 @@
-echo "Welcome to the bumblebee installation v."$BUMBLEBEEVERSION
-echo "Licensed under Red Bull, BEER-WARE License and GPL"
-echo
-echo "This will enable you to utilize both your Intel and nVidia card"
-echo
-echo "Please note that this script will probably only work with Ubuntu, Debian,"
-echo "OpenSuSE and Fedora based machines"
-echo
-echo "Are you sure you want to proceed ? (y/n)"
-
-read answer
-
-case "$answer" in
-  y | Y )
-    ;;
-  
-  *)
-    exit 0
-    ;;
-esac
+#!/bin/bash
+if ! $UNATTENDED; then
+	echo "Welcome to the installation of Bumblebee version $(cat VERSION)"
+	echo "Licensed under Red Bull, BEER-WARE License and GPL"
+	echo
+	echo "This will enable you to utilize both your Intel and nVidia card"
+	echo
+	echo "Please note that this script will probably only work with Ubuntu, Debian,"
+	echo "OpenSuSE and Fedora based machines"
+	echo
+	echo "Are you sure you want to proceed ? (y/n)"
+	read answer
+	if [[ $answer != [yY]* ]]; then
+		echo "Installation aborted"
+	fi
+fi
